category = {'Countries':['Afghanistan','Albania','Algeria','Andorra','Angola','Argentina','Armenia','Australia','Austria','Azerbaijan',
'Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize','Benin','Bhutan','Bolivia','Bosnia Herzegovina','Botswana',
'Brazil','Brunei','Bulgaria','Burkina','Burundi','Cambodia','Cameroon','Canada','Cape Verde','Central African','Chad','Chile','China',
'Colombia','Comoros','Congo','Costa Rica','Croatia','Cuba','Cyprus','Czech Republic','Denmark','Djibouti','Dominica',
'Dominican Republic','East Timor','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Ethiopia','Fiji','Finland',
'France','Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea Bissau','Guyana','Haiti',
'Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy','Ivory Coast','Jamaica','Japan','Jordan',
'Kazakhstan','Kenya','Kiribati','Korea North','Korea South','Kosovo','Kuwait','Kyrgyzstan','Laos','Latvia','Lebanon','Lesotho','Liberia',
'Libya','Liechtenstein','Lithuania','Luxembourg','Macedonia','Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands',
'Mauritania','Mauritius','Mexico','Micronesia','Moldova','Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia',
'Nauru','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria','Norway','Oman','Pakistan','Palau','Panama','Papua New Guinea',
'Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russian Federation','Rwanda','Samoa','San Marino',
'Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Sierra Leone','Singapore','Slovakia','Slovenia','Solomon Islands','Somalia',
'South Africa','South Sudan','Spain','Sri Lanka','Sudan','Suriname','Sweden','Switzerland','Syria','Taiwan','Tajikistan','Tanzania',
'Thailand','Trinidad and Tobago','Tunisia','Turkey','Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom',
'United States','Uruguay','Uzbekistan','Vanuatu','Vatican City','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe'], 
'Sports': ['Baseball','kayaking', 'Curling', 'snowboard','bobsleigh','canoeing','rugby','rafting','surfing',
'synchronized swimming','archery','artistic gymnastics','boxing','basketball','handball','soccer','cycling','fencing',
'figure skating','judo','karate','marathon','rhythmic gymnastics','sprint','wrestling','tennis','badminton','bowling','cricket','curling',
'dodgeball','football','golf','handball','hockey','horseball','hurling','ice hockey','kickball','lacrosse','paddle','polo','racquetball',
'rinkball','rounders','rugby','softball','squash','table tennis','unicycling basketball','unicycling handball','unicycling hockey',
'volleyball','water polo','abseiling','bouldering','gliding','kiteboarding','kitesurfing','parachuting','paragliding','parasailing',
'skateboarding','skydiving','skysurfing','snowboarding','wakeboarding','windsurfing','climbing','cross-country cycling','hiking',
'mountaineering'], 
'Movies': ['The Shawshank Redemption','The Godfather','The Godfather','The Dark Knight','12 Angry Men','Schindler\'s List',
'Pulp Fiction','The Good the Bad and the Ugly','The Lord of the Rings','Fight Club','Star Wars','Forrest Gump','Inception',
'One Flew Over the Cuckoo\'s Nest','Goodfellas','The Matrix','Seven Samurai','City of God','Se7en','The Silence of the Lambs',
'The Usual Suspects','It\'s a Wonderful Life','Life Is Beautiful','The Professional','Once Upon a Time in the West','Interstellar',
'Saving Private Ryan','American History X','Spirited Away','Casablanca','Raiders of the Lost Ark','Psycho','City Lights','Rear Window',
'The Intouchables','Modern Times','Terminator','Whiplash','The Green Mile','The Pianist','Memento','The Departed','Gladiator',
'Apocalypse Now','Back to the Future','The Prestige','Alien','The Lion King','The Lives of Others','The Great Dictator','Inside Out',
'Cinema Paradiso','The Shining','Paths of Glory','Django Unchained','The Dark Knight Rises','WALL E','American Beauty',
'Grave of the Fireflies','Aliens','Citizen Kane','North by Northwest','Princess Mononoke','Vertigo','Oldeuboi','Das Boot',
'Once Upon a Time in America','Amelie','Witness for the Prosecution','Reservoir Dogs','Braveheart','Toy Story','A Clockwork Orange',
'Double Indemnity','Taxi Driver','Requiem for a Dream','To Kill a Mockingbird','Lawrence of Arabia','Eternal Sunshine of the Spotless Mind',
'Full Metal Jacket','The Sting','Amadeus','Bicycle Thieves','Singin\' in the Rain','Monty Python and the Holy Grail','Snatch','The Kid',
'For a Few Dollars More','The Apartment','Inglourious Bastards','All About Eve','The Treasure of the Sierra Madre','Indiana Jones',
'Metropolis','The Third Man','Batman Begins','Scarface','Some Like It Hot','Unforgiven','3 Idiots','Up','Raging Bull','Downfall',
'Mad Max','Jagten','Chinatown','The Great Escape','Die Hard','Good Will Hunting','Heat','On the Waterfront','Pan\'s Labyrinth',
'The Bridge on the River Kwai','My Neighbor Totoro','The Gold Rush','The Seventh Seal','Blade Runner','The Secret in Their Eyes',
'Wild Strawberries','The General','Casino','The Wolf of Wall Street','Gran Torino','V for Vendetta','The Big Lebowski','Rebecca',
'Judgment at Nuremberg','A Beautiful Mind','Cool Hand Luke','The Deer Hunter','How to Train Your Dragon','Gone with the Wind',
'Fargo','Trainspotting','It Happened One Night','Dial M for Murder','Into the Wild','Gone Girl','The Sixth Sense','Rush','Finding Nemo',
'No Country for Old Men','The Thing','Incendies','Hotel Rwanda','Kill Bill','Life of Brian','Platoon','The Wages of Fear',
'Butch Cassidy and the Sundance Kid','There Will Be Blood','Network','Touch of Evil','12 Years a Slave','The Princess Bride',
'The Grand Budapest Hotel','Sin City','The Wizard of Oz','The Bourne Ultimatum','The Best Years of Our Lives','Donnie Darko',
'Jurassic Park','The Avengers','Before Sunrise','Twelve Monkeys','Infernal Affairs','Jaws','The Battle of Algiers',
'Guardians of the Galaxy','Monsters Inc','Harry Potter','The Truman Show','Rocky','The Imitation Game','Pirates of the Caribbean',
'Beauty and the Beast','Before Sunset','Anatomy of a Murder','Akira'],
'Bands': ['ABBA','AC/DC','Aerosmith','The Allman Brothers Band','Amadou and Mariam','The Andrews Sisters','The Animals','Arcade Fire',
'The Band','The Beach Boys','The Beastie Boys','The Beatles','The Bee Gees','Big Star','Black Flag','Black Sabbath','Blondie',
'Boston','The Boswell Sisters','Buffalo Springfield','The Byrds','Calle 13','The Chemical Brothers','Chicago','The Clash','The Coasters',
'Coldplay','Alice Cooper','Cream','Creedence Clearwater Revival','Daft Punk','De La Soul','Death Cab for Cutie','The Decemberists',
'Def Leppard','Devo','The Dillards','Dion and the Belmonts','Dire Straits','Dixie Chicks','The Doors','The Drifters','The Eagles',
'Earth Wind and Fire','Emerson Lake and Palmer','The Everly Brothers','The Flamingos','Fleetwood Mac','The Flying Burrito Brothers',
'The Four Seasons','The Four Tops','Fugazi','The Gang of Four','Genesis','Grandmaster Flash and the Furious Five','The Grateful Dead',
'Green Day','Guns N Roses','The Hollies','Iggy and the Stooges','The Ink Spots','The Isley Brothers','The Jam','The Jefferson Airplane',
'The Jesus and Mary Chain','Jonas Brothers','Joy Division','The Kingston Trio','The Kinks','Gladys Knight and the Pips',
'Kool and the Gang','Kraftwerk','Ladysmith Black Mambazo','Led Zeppelin','Little Anthony and the Imperials','The Louvin Brothers','Love',
'Frankie Lymon and the Teenagers','Lynyrd Skynyrd','The MC5','The Mamas and the Papas','The Mekons','Metallica','The Mills Brothers',
'Modest Mouse','The Monkees','The Moody Blues','The Moonglows','My Chemical Romance','New Order','The New York Dolls','Nine Inch Nails',
'Nirvana','The Ohio Players','One Direction','OutKast','Pearl Jam','The Pet Shop Boys','Pink Floyd','Pixies','The Platters','The Police',
'Public Enemy','Queen','Radiohead','Rage Against the Machine','The Ramones','Red Hot Chili Peppers','The Replacements',
'The Rolling Stones','Santana','The Sex Pistols','The Shadows','The Smiths','Spice Girls','Stanley Brothers','The Strokes','The Temptations',
'Van Halen','The Velvet Underground','The Ventures','The White Stripes','The Who','ZZ Top']}
